### ISSUE TITLE
Crash when using marketplace

### ISSUE THREAD

**Issue by Riesenmumpitz** [AnnoDesigner/anno-designer#197] opened 2020-05-31 15:00 UTC
Hi folks

### Error description
Sadly I am encountering a crashing error every time I try using the Anno 1800 market place (does not matter weather I try to place it normally from the menu or copy paste it) with the following log:
https://pastebin.com/gbUfkmZR

### Reproduction (sort of):
I'm not sure, but I think I was experimenting with giving buildings other colors than they normally have and now every time I spawn a market place from the menu it turns out gray instead of its old color and the designer crashes instantly 😭 

### Solution attempt
I tried to get rid of the error by removing the program code, unpack it again from the zip.. but that did not change anything.. so there must be any persistent settings data somewhere... where is that? 😄 maybe deleting that would help?

I hope I can help improve the designer 😄 NICE WORK anyway 👍 thx take care

**Comment by StingMcRay** [comment] 2020-05-31 15:09
Abt the color changing : it seams i forgot to give the marketplace a standard color... will be fixed as soon as i release the new presets/color json files

**Comment by AgmasGold** [comment] 2020-05-31 15:10
I don't think we store anything that may cause that in user settings - if you want to double check, you can reset the user settings by deleting the `C:\Users\<your user name>\AppData\Local\AnnoDesigner` folder.

I am able to reproduce this - its this building specifically:
![image](https://user-images.githubusercontent.com/48861520/83355712-2bc57880-a359-11ea-9225-00dd2981dc8e.png)

**Comment by AgmasGold** [comment] 2020-05-31 15:10
Turning off the "Show True Influence Range" option stops the issue.

**Comment by AgmasGold** [comment] 2020-05-31 15:56
Looks like its caused when the first building placed is an Anno 1800 building and it has an influence radius.

The call to `max()` throws an exception as `AnnoCanvas.PlacedObjects` is empty when RenderObjectInfluenceRadius is called. The `PlacedObjects` list is then used in the erroring code.

**Comment by Riesenmumpitz** [comment] 2020-05-31 17:52
@AgmasGold oh.. turning off that feature is sad :( as I really like it and it is really useful for optimizing city layout 😉 But thx anyway for the info.
Is there anything I can help you with?

**Comment by AgmasGold** [comment] 2020-05-31 17:58
You should be able to switch it back on again once you have at least one other building that doesn't have an influence range placed onto the screen. We already have a fix created that will be in the next release.

**Comment by Riesenmumpitz** [comment] 2020-06-01 08:59
@AgmasGold actually I tried out to disable the true influence radius.. but the crash keeps coming up. I also removed the `C:\Users\<your user name>\AppData\Local\AnnoDesigner` - files.. still no change. I uploaded my file so maybe you can find another clue :)
[Ultimatives Zentrumsviertel V2.zip](https://github.com/AnnoDesigner/anno-designer/files/4710354/Ultimatives.Zentrumsviertel.V2.zip)
When loading the file I cal easily reproduce the crash by dragging a select rectangle over a huge area covering several streets and the 2 buildings.

**Comment by FroggieFrog** [comment] 2020-06-01 17:20
@Riesenmumpitz I think I could reproduce the issue.
When opening your layout quickly selecting and unselecting buildings there could be a crash.
This should also be fixed with PR #199.
I also think it is unrelated to your original issue.

If you want to give it a try you could use a version which is based on PR #199:
[Anno.Designer.PR199.zip](https://github.com/AnnoDesigner/anno-designer/files/4712565/Anno.Designer.PR199.zip)

Please give it a try and give feedback. As you are still having troubles I reopen the issue.

**Comment by Riesenmumpitz** [comment] 2020-06-01 21:51
@FroggieFrog I just tried PR199 out and it works fine 😃

- loading my file
- placing the market place in it or a new file
- turning the option true **influence radius** on
nice 👍

**Comment by FroggieFrog** [comment] 2020-06-02 04:49
I'm glad we could help.
The next official update will of course contain those fixes. So please update if it available.

**Closed** 2020-06-02 04:49 UTC
Labels: anno canvas, bug, in development, workaround available
